# Generated by Django 3.0.2 on 2020-06-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_supervisor', to='vuz.Emploe'),
        ),
    ]
